CREATE TABLE [USER] (
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	EMAIL VARCHAR(64),
	[PASSWORD] VARCHAR(32)
);

CREATE TABLE [SONG] (
    ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[NAME] VARCHAR(32),
	SINGER VARCHAR(32),
	GENRE VARCHAR(32),
	RELEASE VARCHAR(8),
	YOUTUBE_URL VARCHAR(256),
);

CREATE TABLE [RELATIONS] (
	ID_USER INT FOREIGN KEY REFERENCES [USER](ID),
	ID_SONG INT FOREIGN KEY REFERENCES [SONG](ID)
);


INSERT INTO [USER] VALUES('Daniel', 'pass4');
INSERT INTO [USER] VALUES('Dancho', 'tutrakan');

INSERT INTO [SONG] VALUES('V6', 'tutrakan', 'lel0', '1895', 'www.youtube.com/song=5');
INSERT INTO [SONG] VALUES('V8', 'tutrakan', 'lel0', '1895', 'www.youtube.com/song=5');
INSERT INTO [SONG] VALUES('I6', 'tutrakan', 'lel0', '1895', 'www.youtube.com/song=5');
INSERT INTO [SONG] VALUES('tuci slait', 'tutrakan', 'lel0', '1895', 'https://www.youtube.com/watch?v=eqMj9DTQcAQ');


SELECT * FROM [USER];
SELECT * FROM [SONG];
INSERT INTO [RELATIONS] VALUES (1, 1);
INSERT INTO [RELATIONS] VALUES (1, 3);
INSERT INTO [RELATIONS] VALUES (2, 2);
INSERT INTO [RELATIONS] VALUES (2, 3);
SELECT * FROM RELATIONS;

SELECT *
FROM [SONG]
JOIN RELATIONS ON SONG.ID = RELATIONS.ID_SONG
JOIN [USER] ON [USER].ID = RELATIONS.ID_USER
WHERE [USER].EMAIL = 'Daniel';